services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434

  monitoring-app:
    build: .
    container_name: monitoring-app
    restart: unless-stopped
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
      - /app/extractions
      - /app/__pycache__
    ports:
      - "8484:8484"
    mem_limit: 1g
    memswap_limit: 1g
    cpus: "1.5"

volumes:
  ollama: